name: Build Go project

on:
  workflow_call:
    secrets:
      ssh-private-keys:
        required: false

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    env:
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      ssh-private-keys: ${{ secrets.ssh-private-keys }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check for proto files
      run: |
        if find . -name "*.proto" | grep -q .; then
          echo "proto=true" >> $GITHUB_ENV
          echo ":information_source: Proto files found" >> $GITHUB_STEP_SUMMARY
        else
          echo "proto=false" >> $GITHUB_ENV
          echo ":no_entry_sign: No proto files found" >> $GITHUB_STEP_SUMMARY
        fi

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.x'

    - name: Set up access to private repositories
      if: ${{ env.ssh-private-keys != '' }}
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ env.ssh-private-keys }}

    - name: Go mod tidy check
      run: |
        MOD_DIFF=0
        while read F; do
          cd "$(dirname "$F")" &>/dev/null
          pwd
          if ! go mod tidy -diff; then
            echo "::error file=$F::changes needed"
            MOD_DIFF=1
          fi
          cd - &>/dev/null
        done <<< "$(find . -type f -name go.mod)"
        [ "$MOD_DIFF" -eq 1 ] && exit 1
        echo ":white_check_mark: Go mod tidy check OK" >> $GITHUB_STEP_SUMMARY

    - name: Set up protoc
      if: ${{ env.proto == 'true' }}
      uses: arduino/setup-protoc@v3

    - name: Set up protoc plugins
      if: ${{ env.proto == 'true' }}
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
        export PATH="$(go env GOPATH)/bin:$PATH"

    - name: Compile proto files
      if: ${{ env.proto == 'true' }}
      run: |
        find . -name "*.proto" -exec \
          protoc --go_out=. --go_opt=paths=source_relative \
          --go-grpc_out=. --go-grpc_opt=paths=source_relative {} \;
        echo ":white_check_mark: Compiled proto files" >> $GITHUB_STEP_SUMMARY

    - name: Build
      run: |
        go build
        echo ":white_check_mark: Go package compiled" >> $GITHUB_STEP_SUMMARY

    - name: Test
      run: |
        go test -v ./...
        echo ":white_check_mark: Go test completed" >> $GITHUB_STEP_SUMMARY

