name: Update deployment repository

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      commit:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    concurrency:
      group: deploy-${{ inputs.service }}
      cancel-in-progress: true
    steps:
    - name: Checkout deployment repository
      uses: actions/checkout@v4
      with:
        repository: kaipot/cloud-deployments
        ssh-key: ${{ secrets.CLOUD_DEPLOY_KEY }}

    - name: Update deployment repository
      run: |
        COMMIT_FILE="${{ inputs.service }}/commit"
        echo "OLD_COMMIT=(none)" >> $GITHUB_ENV
        [ -f "$COMMIT_FILE" ] && echo "OLD_COMMIT=$(cat "$COMMIT_FILE")" >> $GITHUB_ENV
        if [ "$OLD_COMMIT" = "${{ inputs.commit }}" ]; then
          echo "::error ::New commit is same as current commit"
          exit 1
        fi
        echo "::notice ::Updating commit for ${{ inputs.service }} from ${{ OLD_COMMIT }} to ${{ inputs.commit }}"
        git config user.email "githubaction@dummy.com"
        git config user.name "GitHub Action"
        echo "${{ inputs.commit }}" > "$COMMIT_FILE"
        git add -A
        git commit -m "Update ${{ inputs.service }} commit to ${{ inputs.commit }}"
        git push

