name: Update deployment repository

on:
  workflow_call:
    inputs:
      service:
        type: string
      commit:
        type: string
    secrets:
      deployment-repository-key:
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    concurrency:
      group: deploy-${{ inputs.service }}
      cancel-in-progress: true
    steps:
    - name: Checkout deployment repository
      uses: actions/checkout@v4
      with:
        repository: kaipot/cloud-deployments
        ssh-key: ${{ secrets.deployment-repository-key }}

    - name: Update deployment repository
      run: |
        COMMIT_FILE="${{ inputs.service }}/commit"
        OLD_COMMIT="(none)"
        if [ -f "$COMMIT_FILE" ]; then
          OLD_COMMIT="$(cat "$COMMIT_FILE")"
          if [ "$OLD_COMMIT" = "${{ inputs.commit }}" ]; then
            echo "::error ::New commit is same as current commit"
            exit 1
          fi
        fi
        git config user.email "githubaction@dummy.com"
        git config user.name "GitHub Action"
        echo "${{ inputs.commit }}" > "$COMMIT_FILE"
        git add -A
        git commit -m "Update ${{ inputs.service }} commit to ${{ inputs.commit }}"
        git push
        echo ":rocket: Updated commit for ${{ inputs.service }} " \
          "from [\`$OLD_COMMIT\`](https://github.com/kaipot/${{ inputs.service }}/tree/$OLD_COMMIT) " \
          "to [\`${{ inputs.commit }}\`](https://github.com/kaipot/${{ inputs.service }}/tree/${{ inputs.commit }})" \
          >> $GITHUB_STEP_SUMMARY

